sudo: required
language: rust
dist: trusty
addons:
  apt:
    packages:
       libssl-dev
cache: cargo
env:
  - ELEFREN_FEATURES="--features toml"
  - ELEFREN_FEATURES="--features all"
  - ELEFREN_FEATURES=""
rust:
  - stable
  - beta
  - nightly
before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly"* ]]; then rustup component add rustfmt-preview; fi
script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly"* ]]; then cargo fmt --all -- --check; fi
  - cargo test $ELEFREN_FEATURES
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]] 2> /dev/null && [ -z "$ELEFREN_FEATURES" ]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --features toml
  fi
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
