sudo: required
language: rust

addons:
  apt:
    packages:
      - libssl-dev
cache:
  directories:
    - $HOME/.cargo
env:
  matrix:
    - ELEFREN_FEATURES="--features toml"
    - ELEFREN_FEATURES="--features json"
    - ELEFREN_FEATURES="--features all"
    - ELEFREN_FEATURES=""

script:
  - cargo test $ELEFREN_FEATURES

matrix:
  include:
    - os: osx
    - os: linux
    - rust: stable
    - rust: beta
    - rust: nightly

    - name: "Coverage"
      rust: nightly
      before_cache: RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install -f cargo-tarpaulin
      after_success: cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID $ELEFREN_FEATURES
      env:
        - ELEFREN_FEATURES="--features all"

    - name: "rustfmt"
      rust: nightly
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- check

  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never
