version: 2
jobs:
    build:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - restore_cache:
                key: project-cache
            - run:
                name: Stable Build
                command: |
                    cargo --version --verbose
                    cargo build -j 1
            - run:
                name: Stable Test (lib)
                command: cargo test -j 1 --lib
            - run:
                name: Stable Test (doc)
                command: cargo test -j 1 --doc
            - save_cache:
                key: project-cache
                paths:
                    - "~/.cargo"
